-- Migration: Add user settings columns to family_members table
ALTER TABLE family_members 
ADD COLUMN IF NOT EXISTS email VARCHAR(255),
ADD COLUMN IF NOT EXISTS username VARCHAR(255),
ADD COLUMN IF NOT EXISTS dark_mode BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS language VARCHAR(10) DEFAULT 'en',
ADD COLUMN IF NOT EXISTS visibility VARCHAR(20) DEFAULT 'family-only',
ADD COLUMN IF NOT EXISTS data_sharing BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notifications_email BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notifications_push BOOLEAN DEFAULT TRUE;